-- The following script was generated by the SQL Script Assembler (SSAsm) V1.1.0
-- Get your copy today at https://github.com/cryptoknows/ssasm
--
--
set pagesize 1000
set linesize 132
set echo off
prompt
prompt
prompt PRESS ENTER TO BEGIN THE APP_USER SCRIPT SCRIPT EXECUTION
accept abc
set echo off
 
set echo off 
!tput clear 
prompt  
prompt
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt  
prompt
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
spool /tmp/ss_APP_USER1.txt
prompt ------------------------------------------------------------------------------------------
 
prompt -- CONTENTS OF ./2016-05-02-APP_USER-/1alter.sql EXECUTING BELOW
 
prompt  
prompt  
prompt  
prompt  
prompt  
set echo on
alter table APP_USER.attribute modify (attribute_owner_id number(16));
 
spool off
set echo off
prompt -- READY TO CONTINUE? PRESS ENTER TO PROCEED TO THE NEXT SECTION
accept abc
set echo off
 
set echo off 
!tput clear 
prompt  
prompt
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt  
prompt
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
spool /tmp/ss_APP_USER2.txt
prompt ------------------------------------------------------------------------------------------
 
prompt -- CONTENTS OF ./2016-05-02-APP_USER-/2createindex.sql EXECUTING BELOW
 
prompt  
prompt  
prompt  
prompt  
prompt  
set echo on
CREATE INDEX APP_USER.DOC_DT_IDX ON APP_USER.DOC(MODIFY_DT)
TABLESPACE APP_TS01;
 
spool off
set echo off
prompt -- READY TO CONTINUE? PRESS ENTER TO PROCEED TO THE NEXT SECTION
accept abc
set echo off
 
set echo off 
!tput clear 
prompt  
prompt
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt  
prompt
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
spool /tmp/ss_APP_USER3.txt
prompt ------------------------------------------------------------------------------------------
 
prompt -- CONTENTS OF ./2016-05-13-APP_USER-Modified/alter_feeds.sql EXECUTING BELOW
 
prompt  
prompt  
prompt  
prompt  
prompt  
set echo on
alter table app_user.feeds add install_status varchar2(100)
 
spool off
set echo off
prompt -- READY TO CONTINUE? PRESS ENTER TO PROCEED TO THE NEXT SECTION
accept abc
set echo off
 
set echo off 
!tput clear 
prompt  
prompt
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt  
prompt
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
spool /tmp/ss_APP_USER4.txt
prompt ------------------------------------------------------------------------------------------
 
prompt -- CONTENTS OF ./2016-05-27-APP_USER-/grants.sql EXECUTING BELOW
 
prompt  
prompt  
prompt  
prompt  
prompt  
set echo on
grant select on APP_USER.FRISBEE to APP_USERS;
 
spool off
set echo off
prompt -- READY TO CONTINUE? PRESS ENTER TO PROCEED TO THE NEXT SECTION
accept abc
prompt  
prompt  
prompt  
prompt  
prompt  
prompt -- END OF RELEASE SCRIPT REACHED. CONGRATULATIONS!
