-- The following script was generated by the SQL Script Assembler (SSAsm) V1.1.0
-- Get your copy today at https://github.com/cryptoknows/ssasm
--
--
set pagesize 1000
set linesize 132
set echo off
prompt
prompt
prompt PRESS ENTER TO BEGIN THE REPORT_USER SCRIPT SCRIPT EXECUTION
accept abc
set echo off
 
set echo off 
!tput clear 
prompt  
prompt
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt  
prompt
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
prompt 
spool /tmp/ss_REPORT_USER1.txt
prompt ------------------------------------------------------------------------------------------
 
prompt -- CONTENTS OF ./2016-05-22-REPORT_USER-/grants.sql EXECUTING BELOW
 
prompt  
prompt  
prompt  
prompt  
prompt  
set echo on
ALTER TABLE REPORT_USER.STAGING ADD (NOTE  VARCHAR2(4000));
 
spool off
set echo off
prompt -- READY TO CONTINUE? PRESS ENTER TO PROCEED TO THE NEXT SECTION
accept abc
prompt  
prompt  
prompt  
prompt  
prompt  
prompt -- END OF RELEASE SCRIPT REACHED. CONGRATULATIONS!
